
import { Formula } from './types';

export const DERIVATIVES: Formula[] = [
  { id: 'd1', question: "(C)'", answer: "0" },
  { id: 'd2', question: "(x)'", answer: "1" },
  { id: 'd3', question: "(x²)'", answer: "2x" },
  { id: 'd4', question: "(x³)'", answer: "3x²" },
  { id: 'd5', question: "(xⁿ)'", answer: "n·xⁿ⁻¹" },
  { id: 'd6', question: "(1/x)'", answer: "−1/x²" },
  { id: 'd7', question: "(√x)'", answer: "1/(2√x)" },
  { id: 'd8', question: "(sin x)'", answer: "cos x" },
  { id: 'd9', question: "(cos x)'", answer: "−sin x" },
  { id: 'd10', question: "(tan x)'", answer: "1/cos²x" },
  { id: 'd11', question: "(eˣ)'", answer: "eˣ" },
  { id: 'd12', question: "(aˣ)'", answer: "aˣ ln a" },
  { id: 'd13', question: "(ln x)'", answer: "1/x" },
  { id: 'd14', question: "(logₐ x)'", answer: "1/(x ln a)" },
  { id: 'd15', question: "(k·f)'", answer: "k·f'" },
  { id: 'd16', question: "(f+g)'", answer: "f'+g'" },
  { id: 'd17', question: "(x⁻¹)'", answer: "−x⁻²" },
  { id: 'd18', question: "(x⁴)'", answer: "4x³" },
  { id: 'd19', question: "(x⁵)'", answer: "5x⁴" },
  { id: 'd20', question: "(x⁶)'", answer: "6x⁵" },
];

export const ANTIDERIVATIVES: Formula[] = [
  { id: 'a1', question: "∫C dx", answer: "Cx + C" },
  { id: 'a2', question: "∫x dx", answer: "x²/2 + C" },
  { id: 'a3', question: "∫x² dx", answer: "x³/3 + C" },
  { id: 'a4', question: "∫x³ dx", answer: "x⁴/4 + C" },
  { id: 'a5', question: "∫xⁿ dx", answer: "xⁿ⁺¹/(n+1) + C" },
  { id: 'a6', question: "∫1/x dx", answer: "ln|x| + C" },
  { id: 'a7', question: "∫√x dx", answer: "2/3·x³ᐟ² + C" },
  { id: 'a8', question: "∫sin x dx", answer: "−cos x + C" },
  { id: 'a9', question: "∫cos x dx", answer: "sin x + C" },
  { id: 'a10', question: "∫1/cos²x dx", answer: "tan x + C" },
  { id: 'a11', question: "∫eˣ dx", answer: "eˣ + C" },
  { id: 'a12', question: "∫aˣ dx", answer: "aˣ/ln a + C" },
  { id: 'a13', question: "∫k·f dx", answer: "k∫f dx" },
  { id: 'a14', question: "∫(f+g) dx", answer: "∫f dx + ∫g dx" },
  { id: 'a15', question: "∫0 dx", answer: "C" },
  { id: 'a16', question: "∫1 dx", answer: "x + C" },
  { id: 'a17', question: "∫x⁻¹ dx", answer: "ln|x| + C" },
  { id: 'a18', question: "∫x⁴ dx", answer: "x⁵/5 + C" },
  { id: 'a19', question: "∫x⁵ dx", answer: "x⁶/6 + C" },
  { id: 'a20', question: "∫x⁶ dx", answer: "x⁷/7 + C" },
];
